name: ininja
recipe: laravel
config:
  php: 7.4
  webroot: public
services:
  appserver:
    xdebug: true
    config:
      php: .vscode/php.ini
  node:
    type: node
    build:
      - npm install
tooling:
  node:
    service: node
  npm:
    service: node